config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  get 'reports', to:'report#index'
  get 'report/index'
  get 'report/exportar'
  post 'report/exportar'
  
  get 'calendar/index'
  resources :registers
  resources :employees
  devise_for :views
  devise_for :users
  root to: 'main#index'
  get 'home/index'
  #root to: 'home#index'

  post 'employees/up'
  post 'employees/down'
  
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :employee

  def self.to_csv
    CSV.generate do |csv|
      csv << ["ID", "Empleado", "Fecha", "Hora de entrada", "Hora de salida", "Total de horas de trabajo"]
      total = 0
      all.each do |r|
        if r.hour_end != nil 
          total += r.total_hours
        end
        csv << [
          r.id, "#{r.employee.full_name}", r.date, 
          r.hour_start.strftime("%I:%M %p"), r.hour_end == nil ? 'Aún trabajando':r.hour_end.strftime("%I:%M %p"), 
          r.total_hours ]
        
      end
      csv << []
      csv << ["Total de horas trabajadas: ", total]
    end
  end

  validates :date, uniqueness: { scope: [:employee_id] }  
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:new, :show, :create]

  before_action :set_register, only: %i[ show edit update destroy ]
  
  layout "free", only: [:new, :show, "errores"]


  # GET /registers or /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1 or /registers/1.json
  def show
  end


  # GET /registers/new
  def new
    @register = Register.new
    @employees = Employee.all
  end

  # GET /registers/1/edit
  def edit
  end

  def errores
    render layout: false
  end

  # POST /registers or /registers.json
  def create
      @er = Array.new
      
      #FECHA
      @day = register_params["date(1i)"].to_i 
      @month = register_params["date(2i)"].to_i
      @year = register_params["date(3i)"].to_i
      @date = Date.new(@day, @month, @year)
     
      #HORA 
      @hour = register_params["hour(4i)"].to_i 
      @seg = register_params["hour(5i)"].to_i
      @time = Time.zone.local(@day,@month,@year, @hour, @seg, 0)

      puts "#{@date}"
      puts "#{@time}"

      @registers = Register.where( employee_id: register_params[:employee_id] , date: @date.all_day)
      
      
      if @registers.length == 0
        if register_params[:tipo] == "S"
          msj =  "Primero debes registrar tu entrada."
          @er = msj
          puts "#{msj}"
        else
          puts "MUY BIEN"
            @register = Register.new
            @register.date = @date
            @register.hour_start = @time
            @register.hour_end = nil
            @register.total_hours = nil
            @register.employee_id = register_params[:employee_id]
        end
      else  
        
        if register_params[:tipo] == "E"
          msj = "La hora de entrada ya ha sido registrada, registre su hora de salida."
          @er = msj
          puts "#{msj}"
        else
          @register = @registers[0]
                  
          if @time <= @register.hour_start
              msj = "La hora de salida no puede ser menor a la hora de entrada"
              @er = msj

              puts "#{msj}"
          else
              puts "REgistrando la salida"
              @register.hour_end = @time
              @register.hour_start = @register.hour_start 
              @register.total_hours = (Time.parse(@register.hour_end.strftime("%Y-%m-%d %H:%M")) - Time.parse(@register.hour_start.strftime("%Y-%m-%d %H:%M")))/3600
          end
        end

      end

      respond_to do |format|
        if @register == nil
          format.html {render "registers/errores.html.erb",:layout => 'nil' }
        elsif @register.save
          puts "AGREDADO"
          format.html { redirect_to @register, :layout=>'nil', notice: "Register was successfully created." }
          format.json { render :show, status: :created, location: @register }
        end
      end
  end

  # PATCH/PUT /registers/1 or /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: "Register was successfully updated." }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1 or /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: "Register was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def register_params
      #params.require(:register).permit(:date, :hour_start, :hour_end, :total_hours, :employee_id)
      params.require(:register).permit(:tipo,:hour,:date , :employee_id)
    end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_form.html.erb
<%= form_with(model: register, local: true) do |form| %>
  <% if register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :tipo , params[:tipo], class:"form-label my-1 d-flex"%>
    <div class="form-check d-flex align-items-center">
      <%= form.radio_button :tipo, 'E', class:"form-check-input", id:"flexRadioDefault2" %>
      <label class="form-check-label mx-2" for="flexRadioDefault2">
        Entrada
      </label>
    </div>
    <div class="form-check d-flex align-items-center">
      <%= form.radio_button :tipo, 'S', class:"form-check-input", id:"flexRadioDefault3" %>
      <label class="form-check-label mx-2" for="flexRadioDefault3">
        Salida
      </label>
    </div>
  </div>

  <div class="field">
    <%= form.label "Fecha", class:"form-label my-1" %>
    <div class="d-flex">
      <%= form.date_select :date, {order: [:day, :month, :year], start_year: 2021}, { class:"form-select"} %>
    </div>

  </div>

  <div class="field my-3">
    <%= form.label "Hora", class:"form-label my-1 " %>
    <div class="d-flex w-50 align-items-center">
      <%= form.time_select :hour,{},{class:"form-select"} %>
    </div>

  </div>

  <div class="field mb-3">
      <label class="form-check-label mr-2 my-1" for="user_rol_id">
        Empleado
      </label>
      <%= form.select(:employee_id, {},{}, {class:"form-select"} )  do%>
        <% @employees.each do |c| -%>
          <%= content_tag(:option, c.full_name, value: c.id) %>
        <% end %>
      <% end %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class:"btn btn-lg btn-success"%>
  </div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editing Register</h1>

<%= render 'form', register: @register %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/errores.html.erb
<div class="card w-50 mx-auto my-5">

    <div class="card-header py-3 d-flex justify-content-between align-items-center">
        <h5 class="">¡Error!</h5>
        <a href="/registers/new" class="btn  btn-dark">
            <i class="bi bi-arrow-90deg-left me-2"></i>
            Regresar
        </a>
    </div>
    <div class="card-body">

        <ul class="p-0">
            <li class="d-flex text-danger">    
                <i class="bi bi-exclamation-diamond me-2"></i>
                <p class="card-text text-start text-danger">
                    <%= @er  %>
                </p>
            </li>
        </ul>
    </div>
        


</div>

app/views/registers/index.html.erb
<p id="notice"><%= notice %></p>


<div class="d-flex justify-content-between">
  <h3>Listado de registros</h3>
</div>

<div class="table-responsive bg-white py-4 rounded-3">

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Fecha</th>
        <th>Hora de entrada</th>
        <th>Hora de salida</th>
        <th>Total de horas</th>
        <th>Empleado</th>
        <!--<th colspan="3"></th>-->
      </tr>
    </thead>

    <tbody>
      <% @registers.each do |register| %>
        <tr>
          <td><%= register.date %></td>
          <td><%= register.hour_start== nil ? '---':register.hour_start.strftime("%I:%M %p") %></td>
          <td><%= register.hour_end== nil ? '---':register.hour_end.strftime("%I:%M %p") %></td>
          <td><%= register.total_hours == nil ? '---':register.total_hours %></td>
          <td><%= register.employee.full_name %></td>
          <!-- <td>
            <%= link_to register, class: "btn btn-success text-white"  do %>
                <i class="bi bi-eye-fill"></i>
            <% end %>
          </td>
         <td><%= link_to 'Show', register %></td>
          <td><%= link_to 'Edit', edit_register_path(register) %></td>
          <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<%= link_to 'New Register', new_register_path %>
          -->
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/registers/new.html.erb
 <div class="w-50 mx-auto my-5 card">
    <div class="card-header">
      <h5>
        <i class="bi bi-plus-square me-2">
        </i> Nuevo Registro
      </h5>
    </div>
    <div class="card-body">
        <%= render 'form', register: @register %>
   </div>
</div>


<!--<%= link_to 'Back', registers_path %>
-->

app/views/registers/show.html.erb
 <div class="w-50 mx-auto my-5 card">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h5 id="notice">
        Registro guardado exitosamente
      </h5>
       <a href="/registers/new", class="btn btn-dark mt-2">
          Regresar
        </a>
    </div>
    <div class="card-body">

        <p class="my-2">
          <strong>ID :</strong>
          <%= @register.id %>
        </p>

          <p>
          <strong>Empleado: </strong>
          <%= @register.employee.full_name %>
        </p>

        <p class="my-2">
          <strong>Fecha :</strong>
          <%= @register.date %>
        </p>


        <p >
          <strong>Hora de entrada :</strong>
          <%= @register.hour_start == nil ? '---':@register.hour_start.strftime("%I:%M %p") %>
        </p>

        <p class="my-2">
          <strong>Hora de salida :</strong>
          <%= @register.hour_end == nil ? '---':@register.hour_end.strftime("%I:%M %p") %>
        </p>

        <p>
          <strong>Total de horas :</strong>
          <%= @register.total_hours  == nil ? '---':@register.total_hours%>
        </p>

       

        <!--<%= link_to 'Editar', edit_register_path(@register) %> -->

       
   </div>
</div>