config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  get 'reports', to:'report#index'
  get 'report/index'
  get 'report/exportar'
  post 'report/exportar'
  
  get 'calendar/index'
  resources :registers
  resources :employees
  devise_for :views
  devise_for :users
  root to: 'main#index'
  get 'home/index'
  #root to: 'home#index'

  post 'employees/up'
  post 'employees/down'
  
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many_attached :documents #Un empleado => tiene varios documentos

    def full_name
        "#{self.try(:name)} #{self.try(:paternalLastName)} #{self.try(:maternalLastName)}"
    end

    def search_name(search)
        Employee.with_attached_documents.references(:documents_attachments).
          where(ActiveStorage::Blob.arel_table[:filename].matches("%#{search}%"))
    end
    
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def up
    @employee = Employee.find(params[:id])
    @employee.update_attribute(:state, true)
    redirect_to employees_path
  end
  
  def down
    @employee = Employee.find(params[:id])
    @employee.update_attribute(:state, false)
    redirect_to employees_path
  end



  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :paternalLastName, :maternalLastName, :state, documents: [])
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Nombre", class:"mb-3" %>
    <%= form.text_field :name , class:"form-control "%>
  </div>

  <div class="field my-3">
    <%= form.label "Apellido Paterno", class:"mb-3" %>
    <%= form.text_field :paternalLastName , class:"form-control"%>
  </div>

  <div class="field">
    <%= form.label "Apellido materno", class:"mb-3" %>
    <%= form.text_field :maternalLastName , class:"form-control"%>
  </div>

  <div class="form-check px-0 my-3 d-flex align-items-center">
    <%= form.label "Estado", class:"form-check-label" %>
    <%= form.check_box :state, class:"form-check-input mx-3", type:"checkbox" %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class:"btn btn-lg btn-success"%>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editar empleado</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-between">
  <h3>Listado de empleados</h3>
  
  <%= link_to new_employee_path, class: "btn btn-light text-center mx-2 text-black" do%>
    <i class="bi bi-plus-lg"></i>
    Nuevo
  <% end %>

</div>

<div class="table-responsive bg-white py-3 rounded-3">

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Estado</th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.id %></td>
          <td>
            <%= employee.full_name %>
          </td>
          <td><%= employee.state ? 'Activo':'Inactivo' %></td>
          <td>
            <%= link_to employee, class: "btn btn-success text-white"  do %>
                <i class="bi bi-eye-fill"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_employee_path(employee), class: "btn btn-warning"  do %>
                <i class="bi bi-pencil-square"></i>
            <% end %>
          </td>
          <!--<td>
            <%= link_to employee,class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Are you sure?' } do%>
                  <i class="bi bi-x-square"></i>
            <% end%>
          </td>-->
          <% if employee.state %>

            <td>
              <%= link_to employees_down_path(:id => employee.id), method: :post, class: "btn btn-dark text-white", title:"Inabilitar" do%>
                <i class="bi bi-stop-circle"></i>
              <% end %>
            </td>

          <% else %>
            <td>
              <%= link_to employees_up_path(:id => employee.id), method: :post,  class: "btn btn-info text-dark", title:"Habilitar" do%>
                <i class="bi bi-play-circle"></i>
              <% end %>
            </td>
          <% end %>
          <td>
            <%= link_to calendar_index_path(:id => employee.id),class: "btn btn-primary text-white", title:"Calendario" do %>
              <i class="bi bi-calendar-fill"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/employees/new.html.erb
<div class="d-flex justify-content-between mb-3">
    <h3 class="">Nuevo Empleado</h3>
</div>

<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-between mb-3">
    <h3 class="">Información de Empleado</h3>

</div>

<div class="card p-3">  

  <div class="card-body">

  <p>
    <strong>Nombre:</strong>
    <%= @employee.full_name %>
  </p>

  <p class="my-3">
    <strong>Estado:</strong>
    <%= @employee.state ? 'Activo':'Inactivo' %>
  </p>
    <%= link_to 'Editar', edit_employee_path(@employee), class:"btn btn-warning text-black" %> 
  </div>

</div>