config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  get 'reports', to:'report#index'
  get 'report/index'
  get 'report/exportar'
  post 'report/exportar'
  
  get 'calendar/index'
  resources :registers
  resources :employees
  devise_for :views
  devise_for :users
  root to: 'main#index'
  get 'home/index'
  #root to: 'home#index'

  post 'employees/up'
  post 'employees/down'
  
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppControlDeviseV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="layout-gen d-flex ">
      <div class="box-nav">
        <div class="title">
          <h5 class=" py-4 px-3 ">Sistema de control</h4>
          <div class="text-start py-3 px-3 username d-flex align-items-center">
              <span class="fs-3">
                  <i class="bi bi-person-circle"></i>
              </span>
              <p class="mx-2 ">
                  Bienvenido <b> <%= current_user.email %> 
              </p>
          </div>        
          <ul class="p-3 nav justify-content-center flex-column">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">
                    <i class="bi bi-speedometer2 me-2"></i>Dashboard
                </a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="/employees"><i class="bi bi-person-bounding-box me-2"></i>Empleados</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/registers"><i class="bi bi-card-checklist me-2"></i>Registros</a>
            </li>

            <li class="nav-item">
                <%= link_to reports_path, class:"nav-link" do%>
                    <i class="bi bi-bookmarks-fill me-2"></i>
                    Reportes
                <% end %>
            </li>

            
          </ul>    
        </div>
      </div>

      <div class="content-main">
        <div class="d-flex justify-content-end py-3 px-4 nav-sup">
          <%= link_to  destroy_user_session_path, method: :delete do %>
              <i class="bi bi-box-arrow-right"></i>
              Salir
          <% end %>
        </div>
        <div class="py-3 px-4">
          <%= yield %>
        </div>
       

      </div>
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppControlDeviseV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="layout-devise hv-100 py-5">
      <div class="content">
        <%= yield %>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/layouts/free.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppControlDeviseV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <%= stylesheet_link_tag "free" %>
  </head>

  <body>
    <header>  
      <div class="container  mx-auto py-4 d-flex justify-content-between align-items-center" > 
          <h3 class="text-white">Registro de entrada y salida - Personal</h3>
          <a href="/" class="text-white fs-3" title="Ir al inicio">
            <i class="bi bi-house-fill"></i>
          </a>
      </div>
    </header>
    <div class="layout-libre d-flex ">

      <div class="container mx-auto ">

       
            <%= yield %>
       
       

      </div>
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppControlDeviseV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <%= stylesheet_link_tag "main" %>
  </head>

  <body>
   
   <div class="home h-100">
    <div class="container text-center mx-auto h-100">
        <div class="d-flex flex-column justify-content-center align-items-center h-100">
            <h3>
                Sistema de control <br> de entrada y salida de personal 
            </h3>
            
            <a href="#" class="title py-3">
                <img height="150" src="https://geosatelital.com/wp-content/uploads/ISOTIPO-BLANCO-PEQUENO.png" alt="Geosatelital">
            </a>
            <div class="enlaces d-flex flex-column">
              <%= link_to home_index_path do %>
                <i class="bi bi-box-arrow-in-right me-2"></i>
                Admin
              <% end %>
              <a href="/registers/new" class="my-2" >
              <i class="bi bi-card-checklist me-2"></i>
                Registrar entrada / Salida
              </a>
            </div>
        </div>
        </div>
    </div>


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/layouts/nil.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppControlDeviseV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

  </head>

  <body style="background:#f9f9f9">
   
  <div class="home h-100 py-5">
    <div class="container text-center mx-auto h-100">
      <%= yield %>
    </div>
  </div>


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>